### ISSUE TITLE
Ctrl-a no longer works on 0.70 in iTerm2

### ISSUE THREAD

**Issue by mscrivo** [pvolok/mprocs#142]
Just updated to 0.70 and it seems Ctrl-a to switch panes no longer works.

This is on a mac (14.5) within latest iterm2.

UPDATE: Another new issue, upon quitting mprocs, my terminal keybindings become messed up. Hitting Ctrl-C results in these char sequences:

```
> ;5;99~;5;99~;5;99
```

until I open a new terminal

**Comment by mscrivo** [comment]
Interestingly it seems to work properly in native terminal app

**Comment by pvolok** [comment]
Seems to be caused by this: https://github.com/pvolok/mprocs/blob/3f73fec805e259a13c0731302854274583b1bad9/src/client.rs#L35

It prints `"\x1b[>4;2m"` escape sequence to make some key combinations work. After some quick reading, I can't find clear explanations of how and where this works. Looks like we have to do some detection here to decide if we should send that sequence. I'll do some more investigation tonight and will roll out a fix asap (even if not perfect).

**Comment by pvolok** [comment]
@mscrivo I disabled above escape sequence only in iTerm2 and released v0.7.1. So it should work now.

But I couldn't find why exactly it is not working in iTerm2. What is interesting is that termwiz crate uses the same escape sequence but it works. But crossterm doesn't.

**Comment by mscrivo** [comment]
Working great! thanks!
