### ISSUE TITLE
Can't scroll history in terminal window

### ISSUE THREAD

**Issue by arifd** [pvolok/mprocs#26]
This is a show stopper unfortunately, as I need to be able to scroll up and see previous logs.

Could we get this implemented?

Many thanks!

**Comment by arifd** [comment]
Ah, okay, doesn't that make ZERO sense though? So `process` has to be focused, and then the terminal window can scroll with cumbersome keystrokes?

Why don't you have left/right arrow keys to focus between `process` and `terminal`, and up/down to scroll history in terminal, or select process in the process list?

If that's not possible, what about the mouse scroll wheel for scrolling the process list, and terminal history when `terminal` is active?

**Comment by pvolok** [comment]
I'm planning to implement mouse scrolling later.

The reason why scrolling is not bound when terminal is focused is because these bindings might conflict with the inner process bindings. So there is only one binding by default: `C-a` to focus process list and all other keys are sent to the inner process. But in the next version you will be able to add your own bindings in either mode.

**Comment by pvolok** [comment]
Yeah, I agree that the current system might be somewhat counterintuitive. The process list mode technically is the read mode and the terminal mode is the write mode.

**Comment by arifd** [comment]
I appreciate your sentiment.

I've been playing with this for the last couple of days now, and navigating (reading) is really a pain, And I want this tool to succeed because it could be so useful! But i'm not sure if I will continue to use this, because it's so fidgety to get to what i need to look at. At least with `concurrently` you can just get good at scrolling around. but if i have something like `cargo watch -x run` and if there's an error in compilation or multiple, it's just such a pain to scroll around, and even harder to get to the command in the first place, and not make a mistake between the focused windows.

Also, the mouse wheel works in the process-list, but one click of the wheel jumps `n` number of entries in the list, so I can't even use it for that.

Since I typically 'read' way more than I 'write', I consider this UX a regression over `concurrently`.

I may consider a fork, but am way happier if I can convince you of this UX design flaw :D

**Comment by pvolok** [comment]
It's possible to see where the mouse pointer is when a user uses mouse wheel. So regardless of the current focus, when the pointer is on top of the process output, the output will be scrolled.

**Comment by serhez** [comment]
The scroll functionality currently provided by `C-u` and `C-d` is not pleasant. It seems it scrolls `x` lines at a time. Being able to configure how many lines to scroll with these commands would be great (I personally would use `x=1`).

Also, I'd love to see mouse scrolling support, this is probably the optimal solution.

Scrolling is probably an important feature for a lot of people, including me, because you may want to have `mprocs` running in a split `tmux` pane, so that the space you have is quite small and scrolling becomes essential, especially when running servers or processes which may show you error traces, etc.

**Comment by pvolok** [comment]
`C-u`/`C-d` scrolls for half the screen height. I like the idea of keys for scrolling by X lines. And the mouse scrolling support will be implemented soon.

**Comment by pvolok** [comment]
Just released mprocs 0.5.0. It adds mouse support (including scrolling) and bindings for scrolling by 3 lines (`C-e`/`C-y`). You can change those bindings in config file:
```yaml
keymap_procs:
  <C-e>: {c: scrol-down-lines, n: 1}
  <C-y>: {c: scrol-up-lines, n: 1}
```

**Comment by arifd** [comment]
> The scroll functionality currently provided by `C-u` and `C-d` is not pleasant. It seems it scrolls `x` lines at a time. Being able to configure how many lines to scroll with these commands would be great (I personally would use `x=1`).

I have to agree with @serhez, jumping 5 lines is awkward. Could we ever change this to 1?

Thanks

**Comment by pvolok** [comment]
Are you talking about mouse or keyboard scrolling?

**Comment by arifd** [comment]
Mouse

**Comment by pvolok** [comment]
I set mouse scroll to 5 lines because that's the behavior of tmux, so it's probably what many people are used to. But I see no problem making it configurable.

**Comment by arifd** [comment]
Well, yeah, if you make it configurable, that works too, thanks! :)
