### ISSUE TITLE
Cargo test fails on vendor example

### ISSUE THREAD

**Issue by taylor1791** [pvolok/mprocs#61]
When I run `cargo test` I get the following error. I am happy to fix it. Is this a PR you would accept? Would you prefer I delete the examples or add portable_pty as a devDependency to `vendor/Cargo.toml`?

```
error[E0432]: unresolved import `portable_pty`
 --> vendor/pty/examples/whoami.rs:5:5
  |
5 | use portable_pty::{CommandBuilder, NativePtySystem, PtySize, PtySystem};
  |     ^^^^^^^^^^^^ use of undeclared crate or module `portable_pty`

error[E0432]: unresolved import `portable_pty`
 --> vendor/pty/examples/whoami_async.rs:3:5
  |
3 | use portable_pty::{native_pty_system, CommandBuilder, PtySize};
  |     ^^^^^^^^^^^^ use of undeclared crate or module `portable_pty`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `mprocs-pty` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `mprocs-pty` due to previous error
```

**Comment by pvolok** [comment]
The `vendor/pty` crate is a fork of the `portable_pty` crate. So the tests should reference their crate. Here I found a way to fix that by specifying the library name: 6e39b1533b15a923e73aabb62f0d0279121acb5f

But there are other tests failing in `vendor/vt100`, which is also a fork of `vt100` crate. But in those failing tests I don't know which behavior would be correct, because it requires to dig deeper into terminal sequences. It seems that in practice things work, so I'm not rushing to fix those tests.

**Comment by GaetanLepage** [comment]
This seems to be fixed with the latest release.

**Comment by pvolok** [comment]
Thanks.
