### ISSUE TITLE
Is there a way to disable mouse select-and-copy?

### ISSUE THREAD

**Issue by drmingdrmer** [pvolok/mprocs#83]
Thanks for this great and simple tool! I've been using it for local testing tasks. I use to select texts on screen with double click to select a word, or triple click to select a line. But it looks like mprocs always enable mouse select thus double click has no effect any more.

I did not find a config entry in the README for disabling mouse select. If it can be disabled it would be more convenient.

Related issue:
-  #47

Thanks!

**Comment by pvolok** [comment]
Thank you, I'm glad you found it useful.

The way terminal apps work with mouse is they request mouse control from terminal. When mouse control is enabled, terminal will send mouse event to the app instead of selecting the text. Here mprocs emulates another terminal inside of it. So the way to let your terminal handle selection is to disable mouse support completely. Or maybe your terminal has a way to enable select mode.

But I think a better way to fix this is to improve selection inside of mprocs. Then mprocs will also let you select a word or a line by double/triple click.

**Comment by drmingdrmer** [comment]
Oh right! This is the right way to solve my problem! Thank you!
